language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm run test
  after_success:
  - npm run coverage
# env:
#   global:
#     - CODECLIMATE_REPO_TOKEN=9341d2e8a53da97e09ff18b1937cf24f431550fde363b113292b450ab68ca1ec